# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92d125922253e03a046bf621e30f75d8ba0ff2b2177c593ffed0cd3617e3c45864b5af5a7b2e848651ef11ba835701b9aa1738a730b7c19fa5e52070e988bc69

test:
  secret_key_base: 34212680a67c566c4cf5e3d201ef23552823996adf13aa1740ac4ca63aa35a2cf5db3568090b7783e590ad1c8c4041d637759ae99b75ed44cdf363cdf8634d0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
